[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.build]
cmds = [
  "python3.10 -m venv /app/.venv",
  "/app/.venv/bin/pip install rasa==3.6.21"
]

[start]
cmd = "/app/.venv/bin/rasa run --enable-api --model models --port $PORT --cors \"*\""
